config/routes.rb
Rails.application.routes.draw do
 
  get 'users/show'
  devise_for :users
  resources :users, only: :show

  resources :books, only: [:show, :index] do
    collection do 
        get "search"
    end
  	resources :reviews, only: [:new, :create, :edit, :update, :destroy] 
  end

  root to: "books#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :book 
	belongs_to :user
	validates :editor, :review, :rank , presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
#タイムライン用のインスタンスを持ってくる
  	def timeline
		@rs = Review.all
	end

#ランキング用のインスタンスの用意	
	def ranking
		book_ids=Review.group(:book_id).order("count_book_id DESC").limit(6).count(:book_id).keys
		@rankings= book_ids.map{ |id| Book.find(id) }
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :timeline, :ranking

  def index
  	@books = Book.order("id DESC").page(params[:page]).per(15)
  end

  def show
  	@book = Book.find(params[:id])
  end

  def search
    @books = Book.where('title LIKE(?)', "%#{params[:keyword]}%").limit(20)
  end

 
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @favorite = Favorite.create(user_id: current_user.id, book_id: params[:book_id])
    @favorites = Favorite.where(book_id: params[:book_id])
    @books = Book.all
  end

  def destroy
    favorite = Favorite.find_by(user_id: current_user.id, book_id: params[:book_id])
    favorite.destroy
    @favorites = Favorite.where(book_id: params[:book_id])
    @books = Book.all
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :timeline, :authenticate_user!, :ranking

  def new
  	@book = Book.find(params[:book_id])
  	@review = Review.new
  end

  def create
  	@book = Book.find(params[:book_id])
  	@review = Review.new(params_review)
  	if @review.save
  		redirect_to book_path(@book)
  	else
  		redirect_to new_book_review_path
  	end
  end

  def edit
  	@book = Book.find(params[:book_id])
  	@review = Review.find(params[:id])
  end

  def update
  	@book = Book.find(params[:book_id])
  	@review = Review.find(params[:id])
  	if @review.update(params_review)
  	#条件分岐
  		redirect_to book_path(@book)
  	else
  		redirect_to edit_book_review_path
  	end
  end

  def destroy
  	@book = Book.find(params[:book_id])
  	@review = Review.find(params[:id])
  	@review.destroy
  	redirect_to book_path(@book)
  end


  private
  def params_review
  	params.require(:review).permit(:editor,  :review, :rank, :book_id, :user_id)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  layout false
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  layout false
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :timeline, :ranking
  before_action :authenticate_user!
  def show
  #current_userを使うので、User.find(current_user.id)はいらないようだ
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/index.html.erb
<div class="title">
<h2>本の一覧</h2>
</div>
<!-- ページネーション -->
<div class="pagenate" %>
	<%= paginate(@books) %>
</div>
<!-- ページネーション終了 -->


<!-- 本情報の一覧を表示 -->
<div id="index">
	<% @books.each do |book| %>
		<div class="book">
			<a href=" books/<%= book[:id] %>"><img src="<%= book.image_url %>" width="180px"></a><br>
			<%= book.title %><br>
			<a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-show-count="false">Tweet</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
		</div>
	<% end %>
</div>

app/views/books/search.html.erb
<h1>search.html.erb</h1>

<%= form_tag('/books/search', method: :get) do %>
   <input class="search__query" name="keyword" placeholder="作品名で検索" type="text" value=""><button class="btn-search" title="検索" type="submit"><i class="icon-search"></i></button></input>
 <% end %>
<!-- 検索結果を表示 -->
 <% @books.each do |book| %>
 	<%= book.title %><br>
 	<img src="<%= book.image_url %>"><br>
 <% end %>

app/views/books/show.html.erb
<h1>Books#show</h1>

<%= @book.title %><br>
<a href="#"><img src="<%= @book.image_url %>"></a><br>

<%= link_to "一覧に戻る", books_path %>
<%= link_to "レビューを書く", "#{@book.id}/reviews/new" %><br>

<!-- review一覧始まり -->
<civ class="reviews">
  <% @book.reviews.each do |review| %>
	  <div class="review">
		投稿者：<%= review.editor %><br>
		レビュー：<%= review.review %><br>
		<%= link_to "レビューを修正する", "#{@book.id}/reviews/#{review.id}/edit" %><br>
		<%= link_to "削除する", book_review_path(@book, review), method: :delete %><br>
		<a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-show-count="false">Tweet</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
	  </div>
	<% end %>
</civ>

app/views/layouts/_footer.html.erb
<p>footer</p>

app/views/layouts/_header.html.erb
<header>
  <div id="logo">
  	<h1><a href="<%= books_path %>">ロゴ</a></h1>
  </div>
  <nav>
  	<div class="global-nav">
  	  <ul>
  	  <% unless user_signed_in? %>
  	  	<li><%= link_to "新規登録", new_user_session_path %></li>
  	  <% end %>
  	  <% if user_signed_in? %>
  	  	<li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
  	  	</li>
        <li><%= link_to "マイページ", users_show_path %></li>
  	  <% end %>
  	  </ul>
  	</div>
  </nav>
</header>

app/views/layouts/_sidebar.html.erb
_sidebar.html.erb

<div id="sidebar">
          <!-- 検索窓 -->
          <%= form_tag('search', method: :get) do %>
             <input class="search__query" name="keyword" placeholder="タイトルで検索" type="text" value="">
             <button class="btn-search" title="検索" type="submit"><i class="icon-search"></i></button></input>
          <% end %>
          <!-- 検索窓終了 -->

          <div class="author">
            <p>作者名一覧</p>
          </div>

          <div class="timeline">
            <p>最近の投稿</p>
            <% @rs.each do |review| %>
              <%= review.editor %>さんの投稿：
              <%= review.review %><br>
            <% end %>
          </div>
      </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookReview</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>


<!-- body始まり -->
  <body>

  <!-- header始まり -->
  <!-- pattial: header -->
  <%= render partial: "layouts/header" %>
  <!-- header終わり -->

  <!-- ランキング始まり -->
  <div id="ranking" >
    <h2>ランキング</h2>
    <% if user_signed_in? %>
    <% @rankings.each.with_index(1) do |ranking,i| %>
      <%= i %>
    
      <img src="<%= ranking.image_url %>" width="200px" >
    <% end %>
    <% end %>
  </div>
  <!-- ランキング終わり -->
  
  <!-- wrapper始まり -->
    <div id="wrapper">
      <div id="content" class="clearfix">
        <div id="main">
          <%= yield %>
        </div>
      
  <!-- sidebar始まり -->
      <% if user_signed_in? %>
        <%= render partial: "layouts/sidebar" %>
      <% end %>
  <!-- sidebar終わり -->

        </div>
        <!-- content終わり -->
    </div>
  <!-- wrapper終わり -->

  <!-- fooer始まり -->
    <footer id="footer">
      <%= render partial: "layouts/footer" %>
    </footer>

  <!-- footer終わり -->
   
  </body>
</html>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/edit.html.erb
<h1>ブックレビューの修正</h1>

<%= form_for ([@book, @review]) do |f| %>
  <%= f.text_field :editor %>
  <%= f.text_area :review %>
  <%= f.number_field :rank, max: 10, min:1 %>
  <%= f.hidden_field :book_id, value: @book.id %>
  <%= f.submit %>
<% end %>

app/views/reviews/new.html.erb
<h1>ブックレビュー</h1>

<%= form_for ([@book, @review]) do |f| %>
  <%= f.text_field :editor %>
  <%= f.text_area :review %>
  <%= f.number_field :rank, max: 10, min:1 %>
  <%= f.hidden_field :book_id, value: @book.id %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.submit %>
<% end %>

app/views/reviews/update.html.erb
<h1>Reviews#update</h1>
<p>Find me in app/views/reviews/update.html.erb</p>

app/views/users/show.html.erb
<h1>マイページ</h1>

<% current_user.reviews.each do |review| %>
  <%= review.review %>
  <img src="<%= review.book.image_url %>", width: 150px >
 <% end %>